### ISSUE TITLE
Crash on MC 1.18.1, also submitted to TKLib and Dynamic Electricity

### ISSUE THREAD

**Issue by Delta4Phoenix** [TechnicalitiesMC/SuperCircuitMaker#9]
Exception in thread "main" java.lang.module.ResolutionException: Modules tklib and supercircuitmaker export package com.technicalitiesmc.lib.circuit.interfaces.wire to module trashcans
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:61)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@0.1.17/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90)

**Comment by Delta4Phoenix** [comment]
0.1.4, the lastest, according to Curseforge

**Comment by amadornes** [comment]
That's really really odd. I just downloaded 0.1.4 and doesn't have any `com.technicalitiesmc.lib` packages anymore, so I don't see how that could be happening...

Could I have the full `latest.log` and `debug.log` files? There might be some more useful info there.

**Comment by HendersonT** [comment]
Here are some log files: Let me know if you think we need to delete some library files or something. When I have time later today I am going to try a new install and run some tests like if running just SCM on what versions causes the crash etc.
[Logs.zip](https://github.com/TechnicalitiesMC/SuperCircuitMaker/files/7856395/Logs.zip)

**Comment by amadornes** [comment]
Now that one's interesting. That pack seems to have multiple versions of several mods, including SCM.

> SereneSeasons-1.18.1-6.0.0.10-universal.jar
> SereneSeasons-1.18.1-6.0.0.8-universal.jar 
> shetiphiancore-1.18-3.10.0.jar 
> shetiphiancore-1.18-3.10.1.jar 
> Shrines-1.18.1-3.0.0-Beta4.jar 
> Shrines-1.18.1-3.0.0-Beta7.jar 
> SuperCircuitMaker2-1.18.1_0.1.0.jar 
> SuperCircuitMaker2-1.18.1_0.1.4.jar 
> [...]

My suspicion here is that when Forge is trying to figure out which of those is the latest version, it's loading both, and the old one is causing issues.

Can you try to see what happens when you manually remove `SuperCircuitMaker2-1.18.1_0.1.0.jar`?

**Comment by XFactHD** [comment]
CurseForge has a bug where it currently doesn't properly delete the old file when updating a mod. They are working on a hotfix right now. For more info see the announcements channel on the CurseForge discord.

**Comment by HendersonT** [comment]
That appears to have fixed the issue, sorry for bothering you with this, I didn't think to look for duplicates since all I had done with this pack was update some mods. I should have payed attention to that, all I saw was SCM attached to the fatal error and assumed that was the issue. Thanks for the help!

**Comment by NillerMedDild** [comment]
I just ran into this issue and I apparently also had several mod jars with different versions in my instance - Removing the older jars fixed the issue, so I'd say you can call this fixed :)

**Comment by amadornes** [comment]
Alrighty, let's call it that then. Thanks! :)

**Comment by Delta4Phoenix** [comment]
Alright, it turned out that Curseforge is being stupid, and when you update a mod, leaves the original jar in the folder. I eventually gave up on hunting them down and remade the modpack manually, and it promptly worked. Sorry for the trouble.
